language: swift
xcode_workspace: Example/JTAppleCalendar.xcworkspace
xcode_scheme: JTAppleCalendar-Example
xcode_sdk: iphonesimulator
env: CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO
notifications:
  email: false
